# Generated by Django 4.0.6 on 2022-08-28 22:56

from django.db import migrations


def create_profiles(app, schema_editor):
    User = app.get_model('auth', "User")
    Profile = app.get_model('accounts', "Profile")
    for user in User.objects.filter(profile__isnull=True):
        Profile.objects.create(user=user)



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_product_profile'),
    ]

    operations = [
        migrations.RunPython(create_profiles, migrations.RunPython.noop)
    ]


